### ISSUE TITLE
How can i add google map location for each Compnay.

### ISSUE THREAD

**Issue by AqibTeam** [LaravelDaily/Laravel-Classimax-Directory#3]
Hi,

- Please can you tell me how can i integrate google map location in each company page. (Like a wallapop on single product page).
- Comments system, review's System etc.

- How can i enable the users registration, for posting ads from user.

Thanks.

**Comment by PovilasKorop** [comment]
Hi,
For all of that it's custom Laravel code, I cannot "just tell you how you can do it".

**Comment by AqibTeam** [comment]
Ok, please can you tell me how can i do?

**Comment by PovilasKorop** [comment]
No, we don't provide such advice for free, sorry.
