### ISSUE TITLE
How add subcategories?

### ISSUE THREAD

**Issue by didi110296** [LaravelDaily/Laravel-Classimax-Directory#4]
Hello, I would like to know how to add a subcategory, I think there is code to add but I would appreciate help because I am a beginner on the Laravel framework. Thanks

**Comment by PovilasKorop** [comment]
@didi110296 we didn't build that function, you probably need to add parent category field in this file - https://github.com/LaravelDaily/Laravel-Classimax-Directory/blob/master/resources/views/admin/categories/create.blade.php

**Comment by didi110296** [comment]
okay thank you
